[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.50"

[context.production.environment]
  HUGO_BASEURL = "https://dev-handbook.netlify.com/"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_ENABLEGITINFO = "true"

[context.branch-deplpy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_ENABLEGITINFO = "true"
